name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7

      - name: Setup PNPM and Install Deps
        id: setup-pnpm
        uses: pnpm/setup@v2.0.2
        with:
          cache: true
          version: 11
          runtime: node@24

      - name: Check Format
        id: pnpm-format-check
        run: pnpm format:check

      - name: Lint
        id: pnpm-lint
        run: pnpm lint

      - name: Test
        id: pnpm-ci-test
        run: pnpm ci-test
